name: GitHub Actions
on:
  push:
  pull_request:
  
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure development happens in feature/* branches
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME="${{ github.ref_name }}"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          fi

          if [[ ! "$BRANCH_NAME" =~ ^feature\/.*$ ]]; then
            echo "Development is only allowed in 'feature/*' branches."
            exit 1
          fi
