name: GitHub Actions
on:
  push:
    - feature/*
  pull_request:
    - main
  
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure development happens in feature/* branches
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [[ ! "$BRANCH_NAME" =~ ^feature\/.*$ ]]; then
            echo "Development is only allowed in 'feature/*' branches."
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: npm ci
      - name: Run linter
        uses: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
  deploy:
    needs: [ lint, test, build ]
    if: github.event_name == "pull_request"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
