name: GitHub Actions
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: './dist'
      - name: Log
        run: |
          echo "Preview URL: ${{ env.NETLIFY_PREVIEW_URL }}"
